import Pagination from "@/components/Pagination";
import SidebarCat from "@/components/SidebarCat";
import BreadCrumb from "@/components/bread-crumb";
import ProductItem from "@/components/productItem";
import { getData } from "@/libs/fetchData";
import { getLoading } from "@/stores/notifyReducer";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { useState } from "react";
import { useDispatch } from "react-redux";
function Product(props) {
  const [products, setProducts] = useState([]);
  const [categories, setCategories] = useState([]);
  useEffect(() => {
    setCategories(props.categories);
    setProducts(props.products);
  }, [props]);
  return (
    <>
      <Head>
        <title>Shops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="shop">
        <BreadCrumb
          value={{ target: "Shop", items: [{ url: "/", name: "Trang chủ" }] }}
        />
        <div className="body">
          <div className="sidebarContainer">
            <SidebarCat categories={categories} />
          </div>
          <div className="productContainer">
            <div className="sort">
              <div className="cmp">Sort</div>
            </div>
            <div className="items">
              {products.length > 0 ? (
                products.map((product, idx) => {
                  return <ProductItem key={idx} product={product} />;
                })
              ) : (
                <div>No product</div>
              )}
            </div>
            <div>
              <Pagination />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export async function getServerSideProps({ query }) {
  let categories = [];
  let products = [];
  const filter = query.filter ? query.filter : "";
  try {
    const categoriesRes = await getData("categories/get-all");
    categories = categoriesRes.data.categories;
  } catch (error) {
    console.log(error);
  }

  try {
    const productsRes = await getData(`products/get-all?filter_by=${filter}`);
    products = productsRes.data.products;
  } catch (error) {
    console.log(error);
  }

  return { props: { categories, products } };
}
export default Product;
