import Pagination from "@/components/Pagination";
import SidebarCat from "@/components/SidebarCat";
import ProductItem from "@/components/productItem";
import { getData } from "@/libs/fetchData";
import Head from "next/head";
import Link from "next/link";

function Product({ categories, products }) {
  return (
    <>
      <Head>
        <title>Shops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="shop">
        <div className="title">
          <div className="content">
            <span className="page">Shop</span>
            <div className="bread-crumb">
              <Link href="/">Trang chủ</Link> &raquo;
              <span>Shop</span>
            </div>
          </div>
        </div>
        <div className="body">
          <div className="sidebarContainer">
            <SidebarCat categories={categories} />
          </div>
          <div className="productContainer">
            <div className="sort">
              <div className="cmp">Sort</div>
            </div>
            <div className="item">
              {products &&
                products.map((product, idx) => {
                  return <ProductItem product={product} key={idx} />;
                })}
            </div>
            <div>
              <Pagination />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export async function getServerSideProps() {
  let categories = [];
  let products = [];

  try {
    const categoriesRes = await getData("categories/get-all");
    categories = categoriesRes.data.categories;
  } catch (error) {
    console.log(error);
  }

  try {
    const productsRes = await getData("products/get-all");
    products = productsRes.data.products;
  } catch (error) {
    console.log(error);
  }

  return { props: { categories, products } };
}
export default Product;
