import ItemContent from "@/components/ItemHome/itemContent";
import NewProducts from "@/components/ItemHome/newProducts";
import SlideImg from "@/components/ItemHome/slide";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Sport GMT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="home">
        <div className="slide">
          <SlideImg />
        </div>
        <div className="shortContent">
          <div className="item">
            <ItemContent />
          </div>
          <div className="item">
            <ItemContent />
          </div>
        </div>
        <div className="new-products">
          <NewProducts />
        </div>
      </div>
    </>
  );
}
