import ItemContent from "@/components/ItemHome/itemContent";
import NewProducts from "@/components/ItemHome/newProducts";
import SlideImg from "@/components/ItemHome/slide";
import { getData } from "@/libs/fetchData";
import { getLoading } from "@/stores/notifyReducer";
import Head from "next/head";
import { useState } from "react";
import { useEffect } from "react";
import { BsStopwatch } from "react-icons/bs";
import { CiDeliveryTruck } from "react-icons/ci";
import { TbExchange } from "react-icons/tb";
import { useDispatch } from "react-redux";
export default function Home() {
  const [posts, setPosts] = useState([]);
  const dispatch = useDispatch();
  useEffect(() => {
    const getPosts = async () => {
      try {
        dispatch(getLoading(true));
        const res = await getData(
          "posts/get-all?sort_by={%22createdAt%22:-1}&page=1&page_size=2"
        );
        dispatch(getLoading(false));
        setPosts(res.data.posts);
      } catch (error) {
        dispatch(getLoading(false));
        console.log(error);
      }
    };
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Sport GMT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="home">
        <div className="slide">
          <SlideImg />
        </div>
        <div className="info-us">
          <div className="info-us-left">
            <div className="info-left-content">
              <span>A LITTLE ABOUT US</span>
              <h2>WHY CHOOSE US</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit
                tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit
                tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
              </p>
              <ul>
                <li>
                  <CiDeliveryTruck className="icon-info" />
                  <span>EXPRESS SHIPPING</span>
                </li>
                <li>
                  <BsStopwatch className="icon-info" />
                  <span>QUICK INSTALLATION</span>
                </li>
                <li>
                  <TbExchange className="icon-info" />
                  <span>30 DAY RETURN POLICY</span>
                </li>
              </ul>
            </div>
          </div>
          <div className="info-us-right">
            <div className="info-image">
              <img
                src="https://cdn.shopify.com/s/files/1/0570/0947/1558/files/banner11.jpg?v=1656921972"
                alt="banner"
              />
            </div>
          </div>
        </div>
        <div className="new-products">
          <div className="title-new">
            <h2>Product New</h2>
            <span>Don't Miss Today's Featured Deals</span>
          </div>
          <NewProducts />
        </div>
        <div className="post-content">
          <div className="title-new">
            <h2>Posts Recent</h2>
            <span>Don't Miss Today's Featured Info</span>
          </div>

          <div className="shortContent">
            {posts.length > 0 ? (
              posts.map((item, idx) => {
                return (
                  <div key={idx} className="item">
                    <ItemContent value={item} name={"blog"} />
                  </div>
                );
              })
            ) : (
              <div>Posts not found!</div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
